# ZSH Path
export ZSH=$HOME/.oh-my-zsh
export EDITOR="emacs"

# Personal settings
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Plugins
plugins=(git docker docker-compose)
plugins+=(node)
plugins+=(nvm)
plugins+=(cabal stack mix pip yarn)


# Theme
ZSH_THEME="avit"
source $ZSH/oh-my-zsh.sh

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

# Do OS specific things
if [[ $OSTYPE == darwin* ]]; then
  plugins+=(osx)

  test -s "$HOME/.kiex/scripts/kiex" && source "$HOME/.kiex/scripts/kiex"
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

  export NIX_PATH=nixpkgs=$NIX_PATH/nixpkgs
  . $HOME/.nix-profile/etc/profile.d/nix.sh
else
  alias switch='sudo nixos-rebuild switch --upgrade'

  # gpg-connect-agent /bye
  # export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
  export PATH="$HOME/.poetry/bin:$PATH"
  eval "$(direnv hook zsh)"

  source ~/.nix-profile/etc/profile.d/hm-session-vars.sh
fi