# Generated by dotspacemacs-used-themes.el
ps:
[
  ps."doom-themes"
  ps."doom-themes"
  ps."doom-themes"
  ps."doom-themes"
  ps."doom-themes"
  ps."doom-themes"
  ps."doom-themes"
  ps."doom-themes"
  ps."doom-themes"
]
