[
  ./core
  ./develop
  ./develop/python
  ./develop/tmux
  ./develop/nix
  ./graphical
  ./graphical/games
  ./graphical/im
  ./graphical/plex.nix
  ./graphical/xmonad
  ./network
  ./network/adblocking.nix
  ./network/networkmanager
  ./network/syncthing
  ./network/stubby.nix
  ./ssh
  ./virt
]
