[
  ./core
  ./graphical
  ./graphical/exwm
  ./graphical/games
  ./graphical/xmonad
  ./network
  ./network/adblocking.nix
  ./network/networkmanager
  ./network/stubby.nix
  ./network/syncthing
  ./ssh
  ./virt
]
